### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by adam-lynch** [stefanjudis/credits#1]
Found when using credits-cli

<img width="486" alt="screen shot 2015-10-26 at 00 58 48" src="https://cloud.githubusercontent.com/assets/1427241/10719229/e63979c8-7b7c-11e5-88e4-0457f227cb76.png">

**Comment by stefanjudis** [comment]
Aah right - I guess you're not running on node `v4.0` or `v0.12`?

**Comment by adam-lynch** [comment]
:+1:

**Comment by stefanjudis** [comment]
???

**Comment by adam-lynch** [comment]
Did you edit that reply? :smile:. v0.10.24

**Comment by stefanjudis** [comment]
Ja sorry. ;) 
Phew - `v0.10`...  

Ja - a promise polyfill should fix that. :)

**Comment by adam-lynch** [comment]
Cool thanks

**Comment by stefanjudis** [comment]
Just saying, that PR's are welcome. ;) 
But will probably tackle this during the week. :bowtie:

**Comment by stefanjudis** [comment]
Fixed with https://github.com/stefanjudis/credits/commit/dd0932fdde1d1238395cfa44a17647f2850dcb94.
